# Generated by Django 4.0.3 on 2022-03-21 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('invoice_date', models.DateField()),
                ('balance_due', models.IntegerField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AddItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('descrition', models.TextField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=40)),
                ('quantity', models.CharField(max_length=255)),
                ('Company_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.companyinvoice')),
            ],
        ),
    ]
