# Generated by Django 4.0.3 on 2022-03-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_companyinvoice_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinvoice',
            name='uid',
            field=models.CharField(max_length=11),
        ),
    ]
